const products = [
  {
    id: 1,
    title: "Mate de Calabaza Tradicional",
    price: 15.99,
    stock: 20,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de calabaza artesanal con virola de aluminio.",
  },
  {
    id: 2,
    title: "Yerba Orgánica",
    price: 9.99,
    stock: 50,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba orgánica sin palo, ideal para un mate suave.",
  },
  {
    id: 3,
    title: "Mate de Vidrio con Funda",
    price: 12.99,
    stock: 15,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de vidrio con funda de cuero, fácil de limpiar.",
  },
  {
    id: 4,
    title: "Yerba con Hierbas",
    price: 11.99,
    stock: 40,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con una mezcla de hierbas naturales.",
  },
  {
    id: 5,
    title: "Bombilla de Alpaca",
    price: 8.99,
    stock: 25,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de alpaca con filtro desmontable.",
  },
  {
    id: 6,
    title: "Mate de Madera Tallado",
    price: 18.99,
    stock: 10,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de madera tallado a mano, único en su estilo.",
  },
  {
    id: 7,
    title: "Yerba Despalada",
    price: 10.99,
    stock: 35,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba despalada, ideal para un mate más fuerte.",
  },
  {
    id: 8,
    title: "Mate de Cerámica",
    price: 14.99,
    stock: 22,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de cerámica pintado a mano, resistente y duradero.",
  },
  {
    id: 9,
    title: "Yerba con Menta",
    price: 12.49,
    stock: 30,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con un toque refrescante de menta.",
  },
  {
    id: 10,
    title: "Bombilla de Bronce",
    price: 7.99,
    stock: 28,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de bronce con diseño clásico.",
  },
  {
    id: 11,
    title: "Mate de Acero Inoxidable",
    price: 16.99,
    stock: 18,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de acero inoxidable, ideal para mantener la temperatura.",
  },
  {
    id: 12,
    title: "Yerba con Limón",
    price: 11.49,
    stock: 45,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con un toque cítrico de limón.",
  },
  {
    id: 13,
    title: "Bombilla de Plata",
    price: 19.99,
    stock: 12,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de plata con detalles ornamentales.",
  },
  {
    id: 14,
    title: "Mate de Cuero",
    price: 17.99,
    stock: 14,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate forrado en cuero, elegante y tradicional.",
  },
  {
    id: 15,
    title: "Yerba con Jengibre",
    price: 12.99,
    stock: 38,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con un toque picante de jengibre.",
  },
  {
    id: 16,
    title: "Bombilla de Acero Inoxidable",
    price: 7.99,
    stock: 30,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de acero inoxidable con filtro desmontable.",
  },
  {
    id: 17,
    title: "Mate de Porcelana",
    price: 13.99,
    stock: 16,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de porcelana con diseño moderno.",
  },
  {
    id: 18,
    title: "Yerba con Naranja",
    price: 11.99,
    stock: 42,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con un toque dulce de naranja.",
  },
  {
    id: 19,
    title: "Bombilla de Aluminio",
    price: 6.99,
    stock: 35,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de aluminio ligera y resistente.",
  },
  {
    id: 20,
    title: "Mate de Vidrio",
    price: 12.49,
    stock: 20,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de vidrio con funda de silicona antideslizante.",
  },
  {
    id: 21,
    title: "Yerba con Canela",
    price: 12.49,
    stock: 37,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con un toque cálido de canela.",
  },
  {
    id: 22,
    title: "Bombilla de Titanio",
    price: 21.99,
    stock: 10,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de titanio, ultra resistente y ligera.",
  },
  {
    id: 23,
    title: "Mate de Aluminio",
    price: 14.49,
    stock: 18,
    img: "/src/assets/products/mate.jpg",
    category: "Mates",
    description: "Mate de aluminio con diseño ergonómico.",
  },
  {
    id: 24,
    title: "Yerba con Lavanda",
    price: 13.49,
    stock: 33,
    img: "/src/assets/products/yerba.jpg",
    category: "Yerba",
    description: "Yerba con un toque relajante de lavanda.",
  },
  {
    id: 25,
    title: "Bombilla de Cobre",
    price: 8.49,
    stock: 27,
    img: "/src/assets/products/bombilla.jpg",
    category: "Accesorios",
    description: "Bombilla de cobre con diseño tradicional.",
  },
];

export default products;